# Git Workflow Rules Configuration
# This enforces the workflow defined in git-workflow-rules.md
# git-workflow-rules.md is the authority - this config implements those rules

# Protected branches - ONLY main is protected per git-workflow-rules.md
# Rule: "Never suggest direct commits to main"
protectedBranches:
  - main

# Integration branch where features are merged first  
# Rule: "All feature branches merge here first" - dev is freely writable
integrationBranch: dev

# Branch prefixes for workflow organization per git-workflow-rules.md
featureBranchPrefix: feature/
hotfixBranchPrefix: hotfix/

# Workflow enforcement settings per git-workflow-rules.md
requireCleanWorkingTree: true
allowDirectPush: false  # Never allow direct pushes to protected branches (main only)

# Commit message validation - matches git-workflow-rules.md format exactly
enforceCommitMessageFormat: true
allowedCommitTypes:
  - feat      # New feature
  - fix       # Bug fix  
  - docs      # Documentation
  - style     # Formatting
  - refactor  # Code restructuring
  - test      # Adding tests
  - chore     # Maintenance